### PR TITLE
Added information for the TM-T88II.

### PR DESCRIPTION
**Pull request by Foaly**
Hi there!
I added more information on the TM-T88II.
If I missed anything let me know!

### CODE REVIEW

**Comment by Foaly** [comment]
Ping! Is something holding this back? :)

**Comment by Foaly** [comment]
Hi!
I would again like to request for this to merged.
I am using a project that depends on this DB (https://github.com/python-escpos/python-escpos)
Right now I have to point the dependancy of python-escpos to my branch, which makes maintaining a whole lot more difficult than it needs to be.
It would be great if this could be merged soon! Thanks a lot :)

**Comment by patkan** [comment]
@Foaly thanks for being insistent, I will look into getting this merged.

@mike42 Do you see anything against merging this one? I will dig out my TM-T88II and have a look, but so far this PR looks good to me.

**Comment by Foaly** [comment]
@patkan Thank you very much for looking into it! I would love to see this merged :)

**Review by patkan — APPROVED** [review]

**Comment by patkan** [comment]
Still looks good to me, and as far as I could test it, seems also OK. :-)

**Pull request merged**
