### PR TITLE
Add NT-5890K profile. added features: paperPartCut and paperFullCut

### PR DESCRIPTION
**Pull request by katyukha**
This pull requests adds profile for NT-5890K
[Specification](http://www.gzxlscan.com/ru/product-detail/nt-5890k-58mm-thermal-receipt-printer/)

Also this pull request introduces two new capabilities:
- `paperFullCut`
- `paperPartCut`

The reason to introduce these capabilities, beacuse some printers, like mentioned one, have not automatic cutter, and not all printers that have automatic cutter, support partial cut.

### CODE REVIEW

**Comment by mike42** [comment]
Your new profile looks good, but I believe this printer may already be included under the name `POS-5890` (It is sold by many companies under their own brand).

The `POS-5890` profile is based on `simple`, because the printer doesn't support QR codes, or the newer graphics commands either. The only other difference i can see is Thai output at code page 70, which is not present on the model I use.

Would you consider updating this to either add the `paperFullCut`, `paperPartCut` entries, `media` and `fonts` to `POS-5890`, or do you think there are enough differences for two separate profiles?

--

Diff below for full context-

```diff
2,7c2,21
< POS-5890:
<   name: POS5890 Series
<   vendor: Zjiang
<   inherits: simple
<   notes: >
<       POS-5890 thermal printer series, also marketed under various other names.
---
> NT-5890K:
>   # Specification: http://www.gzxlscan.com/ru/product-detail/nt-5890k-58mm-thermal-receipt-printer/
>   name: NT-5890K
>   vendor: Netum
>   inherits: default
>   notes: ""
>   features:
>     paperFullCut: false
>     paperPartCut: false
>   fonts:
>     0:
>       name: Font A
>       columns: 32
>     1:
>       name: Font B
>       columns: 42
>   media:
>     width:
>       mm: 57.5
>       pixels: 384
10c24
<     1: CP932
---
>     1: Unknown  # Katakana
15c29
<     # West Europe
---
>     # Western Europe
21c35
<     # East Europe
---
>     # Eastern europe
31c45
<     # Latvian
---
>     # latvian
39c53,54
<     27: CP1258
---
>     # Vietnam
>     27: Unknown
43a59,60
>     # Thai
>     255: Unknown
61a79
>     70: CP874
85c103
<     # Thai 2
---
>     # Thai2
87,89d104
<     # Thai
<     255: Unknown
< ...
```

**Comment by katyukha** [comment]
Encoding with code 70, is my mistake(
And You seems to be right. I will try to rebase this profile on POS-5890, and test it...

**Comment by katyukha** [comment]
POS-5890 is based on profile simple, which have disabled image printing(bitImageColumn, graphics), but, my NT-5890K can print images (bitImageRaster, bitImageColumn)

**Comment by katyukha** [comment]
Does POS-5890 supports barcodes, I've used python-escpos, trying to print barcodes, but it seems that it does not support them?
May be, in addition to `barcodeB` feature add `barcodeA` feature?

**Comment by mike42** [comment]
Good idea, raised a new ticket as #26. Thanks for your contribution katyukha!

**Pull request merged**
